steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/qwen2vl/app:$SHORT_SHA', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qwen2vl-canary'
      - '--image=us-docker.pkg.dev/$PROJECT_ID/qwen2vl/app:$SHORT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--timeout=300'
      - '--max-instances=2'
      - '--min-instances=0'
      - '--concurrency=1'
      - '--set-env-vars=MODEL_DIR=/tmp/models/Qwen2-VL-2B-Instruct,ALLOW_DOWNLOAD=1'
      - '--command=bash'
      - '--args=-lc,uvicorn main:app --host 0.0.0.0 --port ${PORT}'
images:
  - 'us-docker.pkg.dev/$PROJECT_ID/qwen2vl/app:$SHORT_SHA'


