steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=$_FULL_TAG
      - --cache=false
      - --use-new-run
      - --verbosity=info
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
timeout: "3600s"
images:
  - $_FULL_TAG
