# cloudbuild.yaml
steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=$_IMAGE
      - --cache=false
      - --use-new-run
      - --snapshotMode=redo
      - --verbosity=info
options:
  machineType: E2_HIGHMEM_8
  diskSizeGb: 200
timeout: "3600s"
images:
  - $_IMAGE
substitutions:
  _IMAGE: us-docker.pkg.dev/api-colab-demo/qwen2vl/app:latest


