steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=$_IMAGE
      - --cache=false
      - --use-new-run
      - --verbosity=info

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
timeout: "3600s"
images:
  - $_IMAGE
substitutions:
  _IMAGE: us-docker.pkg.dev/api-colab-demo/gcr.io/qwen2vl:baked

